POST http://localhost:8888/accounts
content-type: application/json


{
    "application": "eseler",
    "name": "fsdfdddd13413ddUser",
    "email": "fsdfdddd1343dtestfsdsdse@gmail.com",
    "termAccept": "true"

}

