POST http://localhost:8885/authentication/v1/identifications/refresh
content-type: application/json

{
    "grant_type": "refresh_token",
    "client_id": "eselwer-admin",
    "client_secret": "MpDq1EwelMh4FJB4h37mlvvYQiR6o5Lb",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1ODQzMzkxNS1lNGUzLTRiM2YtYWRjYS1mN2VjZTFiOTU3ZDMifQ.eyJleHAiOjE2ODYxNjAwNjMsImlhdCI6MTY4NTI5NjA2MywianRpIjoiYWFkOGU1OWUtOWY3My00ZTViLTg3NjctODRmZDBjZTIzODE1IiwiaXNzIjoiaHR0cDovLzE5Mi4xNjguMzkuMTU6MzIzMjEvcmVhbG1zL2VzZWx3ZXIiLCJhdWQiOiJodHRwOi8vMTkyLjE2OC4zOS4xNTozMjMyMS9yZWFsbXMvZXNlbHdlciIsInN1YiI6ImY1ZjQzODUwLWJkZGItNGQ4OC04OTcyLTgwNDJlNmNmYjMxZSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJlc2Vsd2VyLWFkbWluIiwic2Vzc2lvbl9zdGF0ZSI6IjgxOTI3ZGYxLTViYzYtNGMxYi04MzI0LTI2ODg4MmQ0Y2I0YSIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI4MTkyN2RmMS01YmM2LTRjMWItODMyNC0yNjg4ODJkNGNiNGEifQ.YtPgye69B3zkRJkYi_HbCpYf7l2WdtnpsRb6GC4t1WI"
}


