POST http://192.168.39.209:32094/realms/eselwer/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

grant_type=password
&client_id=eselwer-admin
&client_secret=TiKbbV64bkGqW7d3hmsFHPCqf1nqiVtV
&username=desenvolvedor
&password=teste
&scope=roles

