POST http://192.168.39.209:30041/authentication/v1/identifications/token
content-type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "eselwer-admin",
    "client_secret": "TiKbbV64bkGqW7d3hmsFHPCqf1nqiVtV",
    "scope": "email roles"

}

