apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app-env
  name: account-configmap
data:  
  PORT: '8080'
  PROFILE: prod
  DB_ADDR: '192.168.15.103'
  DB_DATABASE: account
  DB_USER: ${POSTGRES_USER}
  DB_PASSWORD: ${POSTGRES_PASSWORD}
  DB_JDBC: 'jdbc:postgresql://192.168.15.103:5432/account'
  