apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app-env
  name: keycloak-database-configmap
data:  
  POSTGRES_DB: keycloakdb
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
