apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app-env
  name: keycloak-service-configmap
data:
  DB_PORT: '5435'
  DB_ADDR: keycloak-database-service
  DB_DATABASE: keycloakdb
  DB_PASSWORD: keycloakpwd
  DB_SCHEMA: public
  DB_USER: postgres
  DB_VENDOR: postgres
  DB_JDBC: 'jdbc:postgresql://keycloak-database-service:5435/keycloakdb'
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd    
  