apiVersion: v1
kind: Service
metadata:
  namespace: app-env 
  labels:
    app: gateway-app    
  name: gateway-service
  annotations:
    type: service
    domain: Gateway
    business: Security
  
spec:
  type: LoadBalancer
  selector:
    app: gateway-app
  ports:
    - name: http-porta-web
      protocol: TCP
      port: 8080
      targetPort: 8080  
  sessionAffinity: "ClientIP"
