apiVersion: v1
kind: PersistentVolume
metadata:  
  namespace: app-env
  name: keycloak-database-volume-pv
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: keycloak-database-volume-pvc
    namespace: app-env
  hostPath:
    path: /data/keycloak-data
    type: DirectoryOrCreate
  
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  namespace: app-env  
  labels:
    app: keycloak-database-persistent
  name: keycloak-database-volume-pvc
  annotations:
    type: volume
    domain: keycloak
spec:
  volumeName: keycloak-database-volume-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer