apiVersion: v1
kind: PersistentVolume
metadata:  
  name: keycloak-database-volume-pv
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /keycloak-data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop # must be the name of your node (kubectl get nodes)
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  namespace: app-env  
  labels:
    app: keycloak-database-persistent
  name: keycloak-database-volume-pvc
  annotations:
    type: volume
    domain: keycloak
spec:
  volumeName: keycloak-database-volume-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

