apiVersion: v1
kind: Service
metadata:
  namespace: app-env
  labels:
    app: keycloak-svc
    version: 14.3.0
  name: keycloak-database-service
  annotations:
    type: service
    domain: keycloak
    business: security
spec:
  type: ClusterIP
  ports:    
    - name: tcp-database
      protocol: TCP
      port: 5435
      targetPort: 5432
  selector:
    app: keycloak-database-container
