apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-env
  labels:
    app: auth-server-app-deployment

  name: auth-server-application
  annotations:
    type: app
    domain: auth-server
    business: Security
spec:
  selector:
    matchLabels:
      app: auth-server-app
  template:
    metadata:
      labels:
        app: auth-server-app
    spec:
      containers:
          - name: auth-server-application-container
            image: srochg/auth-server:0.0.1
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "0.5"
                memory: "512Mi"
            env:
            - name: APP_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEYCLOAK_APP_CREDENTIAL_ID
            - name: APP_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEYCLOAK_APP_CREDENTIAL_SECRET
            envFrom:
              - configMapRef:
                  name: auth-base-configmap
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 10
            startupProbe:
              httpGet:
                path: /_app-state/health
                port: 8080
              periodSeconds: 10
              failureThreshold: 30
              successThreshold: 1

            livenessProbe:
              httpGet:
                path: /_app-state/health 
                port: 8080

              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 5
              timeoutSeconds: 5
              successThreshold: 1
              terminationGracePeriodSeconds: 30
      restartPolicy: Always
